#!/usr/bin/env bash

url="http://www.ccfit.nsu.ru/fit/courses/cogpsy/CogPsy2009.7z"

function do_req() {
  curl --no-keepalive --proxy-header "Proxy-Connection:" -x 127.0.0.1:7331 $1 -o $2 &>$3 &
}

do_req $url drop.7z solo_drop.log
pid=$!
sleep 2
kill $pid
