#!/usr/bin/env bash

url1="http://classics.mit.edu/Plato/laws.mb.txt"
url2="http://www.ccfit.nsu.ru/fit/courses/physics/meh_elem_sto.pdf"
url3="http://www.lib.ru/INPROZ/KERUAK/bigsir_engl.txt"

function do_req() {
  curl --no-keepalive --proxy-header "Proxy-Connection:" -x 127.0.0.1:7331 $1 -o $2 &>$3 &
}

do_req $url1 parallel_1.txt parallel_1.log
do_req $url2 parallel_2.pdf parallel_2.log
do_req $url3 parallel_3.html parallel_3.log
