#!/usr/bin/env bash

url="http://classics.mit.edu/Plato/laws.mb.txt"

function do_req() {
  curl --no-keepalive --proxy-header "Proxy-Connection:" -x 127.0.0.1:7331 $1 -o $2 &>$3 &
}

do_req $url 200_1.txt first_200.log
do_req $url 200_2.txt second_200.log
