#!/usr/bin/env bash

url="http://www.ccfit.nsu.ru/fit/courses/cogpsy/CogPsy2009.7z"

function do_req() {
  curl --no-keepalive --proxy-header "Proxy-Connection:" -x 127.0.0.1:7331 $1 -o $2 &>$3 &
}

do_req $url 200_1.7z first_200.log
do_req $url 200_2.7z second_200.log
